apiVersion: v1
kind: Namespace
metadata:
  name: python-app
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: python-app
  labels:
    app.kubernetes.io/name: backend-app
spec:
  containers:
  - name: backend
    image: aprezcuba24/example:1.0
    ports:
      - containerPort: 5000
        name: backend-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: python-app
  name: backend-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend-app
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 80
    targetPort: backend-port
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: python-app
  labels:
    app.kubernetes.io/name: mongo
spec:
  containers:
  - name: mongo
    image: mongo:6.0.2
    ports:
      - containerPort: 27017
        name: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: python-app
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: db-port

