
apiVersion: v1
kind: Namespace
metadata:
  name: aprezcuba24-python-kubernates-example

---

apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: aprezcuba24-python-kubernates-example
  labels:
    app.kubernetes.io/name: mongo
spec:
  containers:
  - name: mongo
    image: mongo:6.0.2
    ports:
      - containerPort: 27017
        name: mongodb-port
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: aprezcuba24-python-kubernates-example
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: mongodb-port

---

apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: aprezcuba24-python-kubernates-example
  labels:
    app.kubernetes.io/name: backend-app
spec:
  containers:
  - name: backend
    image: aprezcuba24/python-kubernates-example:70c9d9051dc56120a2e7e93592bd8c75fcbcf76a
    ports:
      - containerPort: 5000
        name: backend-port
    envFrom:
      - configMapRef:
          name: backend-config-env
---
apiVersion: v1
kind: Service
metadata:
  namespace: aprezcuba24-python-kubernates-example
  name: backend-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend-app
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 80
    targetPort: backend-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: aprezcuba24-python-kubernates-example
  name: backend-config-env
data:
  MONGODB_URI: mongodb://host.minikube.internal:27017/aprezcuba24-python-kubernates-example_db
  PORT: '5000'

